"""
错误码定义

定义所有命令安装器使用的错误码。
"""


class ErrorCode:
    """错误码枚举类"""

    # 来源解析错误 (RESOLVE)
    RESOLVE_INVALID_SOURCE = "RESOLVE_INVALID_SOURCE"
    RESOLVE_UNKNOWN_TYPE = "RESOLVE_UNKNOWN_TYPE"
    RESOLVE_PRESET_NOT_FOUND = "RESOLVE_PRESET_NOT_FOUND"

    # 下载错误 (DOWNLOAD)
    DOWNLOAD_GIT_CLONE_FAILED = "DOWNLOAD_GIT_CLONE_FAILED"
    DOWNLOAD_NETWORK_ERROR = "DOWNLOAD_NETWORK_ERROR"
    DOWNLOAD_TIMEOUT = "DOWNLOAD_TIMEOUT"
    DOWNLOAD_TEMP_DIR_ERROR = "DOWNLOAD_TEMP_DIR_ERROR"

    # 验证错误 (VALIDATE)
    VALIDATE_INVALID_COMMAND_NAME = "VALIDATE_INVALID_COMMAND_NAME"
    VALIDATE_INVALID_VERSION = "VALIDATE_INVALID_VERSION"
    VALIDATE_INVALID_FRONTMATTER = "VALIDATE_INVALID_FRONTMATTER"
    VALIDATE_FILE_ENCODING = "VALIDATE_FILE_ENCODING"
    VALIDATE_CHECKSUM_MISMATCH = "VALIDATE_CHECKSUM_MISMATCH"

    # 安装错误 (INSTALL)
    INSTALL_COMMAND_EXISTS = "INSTALL_COMMAND_EXISTS"
    INSTALL_FILE_CONFLICT = "INSTALL_FILE_CONFLICT"
    INSTALL_COPY_FAILED = "INSTALL_COPY_FAILED"
    INSTALL_PERMISSION_DENIED = "INSTALL_PERMISSION_DENIED"
    INSTALL_DISK_SPACE_INSUFFICIENT = "INSTALL_DISK_SPACE_INSUFFICIENT"

    # 更新错误 (UPDATE)
    UPDATE_NOT_FOUND = "UPDATE_NOT_FOUND"
    UPDATE_NO_UPDATE_AVAILABLE = "UPDATE_NO_UPDATE_AVAILABLE"
    UPDATE_BACKUP_FAILED = "UPDATE_BACKUP_FAILED"
    UPDATE_SOURCE_NOT_FOUND = "UPDATE_SOURCE_NOT_FOUND"

    # 卸载错误 (UNINSTALL)
    UNINSTALL_NOT_FOUND = "UNINSTALL_NOT_FOUND"
    UNINSTALL_DELETE_FAILED = "UNINSTALL_DELETE_FAILED"
    UNINSTALL_HAS_DEPENDENCIES = "UNINSTALL_HAS_DEPENDENCIES"

    # 配置错误 (CONFIG)
    CONFIG_LOAD_FAILED = "CONFIG_LOAD_FAILED"
    CONFIG_SAVE_FAILED = "CONFIG_SAVE_FAILED"
    CONFIG_INVALID_FORMAT = "CONFIG_INVALID_FORMAT"
    CONFIG_LOCK_FAILED = "CONFIG_LOCK_FAILED"

    # 系统错误 (SYSTEM)
    SYSTEM_UNKNOWN_ERROR = "SYSTEM_UNKNOWN_ERROR"
    SYSTEM_INTERRUPTED = "SYSTEM_INTERRUPTED"


# 错误消息映射
ERROR_MESSAGES = {
    ErrorCode.RESOLVE_INVALID_SOURCE: "无效的命令来源",
    ErrorCode.RESOLVE_UNKNOWN_TYPE: "无法识别的来源类型",
    ErrorCode.RESOLVE_PRESET_NOT_FOUND: "预设名称不存在",

    ErrorCode.DOWNLOAD_GIT_CLONE_FAILED: "Git 仓库克隆失败",
    ErrorCode.DOWNLOAD_NETWORK_ERROR: "网络连接失败",
    ErrorCode.DOWNLOAD_TIMEOUT: "操作超时",
    ErrorCode.DOWNLOAD_TEMP_DIR_ERROR: "临时目录创建失败",

    ErrorCode.VALIDATE_INVALID_COMMAND_NAME: "命令名称格式无效",
    ErrorCode.VALIDATE_INVALID_VERSION: "版本号格式无效",
    ErrorCode.VALIDATE_INVALID_FRONTMATTER: "Frontmatter 格式无效",
    ErrorCode.VALIDATE_FILE_ENCODING: "文件编码错误（应为 UTF-8）",
    ErrorCode.VALIDATE_CHECKSUM_MISMATCH: "文件校验和不匹配",

    ErrorCode.INSTALL_COMMAND_EXISTS: "命令已存在",
    ErrorCode.INSTALL_FILE_CONFLICT: "文件冲突",
    ErrorCode.INSTALL_COPY_FAILED: "文件复制失败",
    ErrorCode.INSTALL_PERMISSION_DENIED: "权限不足",
    ErrorCode.INSTALL_DISK_SPACE_INSUFFICIENT: "磁盘空间不足",

    ErrorCode.UPDATE_NOT_FOUND: "命令不存在",
    ErrorCode.UPDATE_NO_UPDATE_AVAILABLE: "没有可用更新",
    ErrorCode.UPDATE_BACKUP_FAILED: "备份创建失败",
    ErrorCode.UPDATE_SOURCE_NOT_FOUND: "无法找到更新源",

    ErrorCode.UNINSTALL_NOT_FOUND: "命令不存在",
    ErrorCode.UNINSTALL_DELETE_FAILED: "文件删除失败",
    ErrorCode.UNINSTALL_HAS_DEPENDENCIES: "命令有依赖项",

    ErrorCode.CONFIG_LOAD_FAILED: "配置文件加载失败",
    ErrorCode.CONFIG_SAVE_FAILED: "配置文件保存失败",
    ErrorCode.CONFIG_INVALID_FORMAT: "配置文件格式无效",
    ErrorCode.CONFIG_LOCK_FAILED: "配置文件锁定失败",

    ErrorCode.SYSTEM_UNKNOWN_ERROR: "未知错误",
    ErrorCode.SYSTEM_INTERRUPTED: "操作被中断",
}


def get_error_message(error_code: ErrorCode) -> str:
    """
    获取错误码对应的消息

    Args:
        error_code: 错误码

    Returns:
        错误消息字符串
    """
    return ERROR_MESSAGES.get(error_code, "未知错误")
